server:
  port: 8080

# The properties structure must match {@link TwilioProperties.java}
twilio:
  # https://www.twilio.com/docs/conversations/create-tokens
  accountSid: ${TWILIO_ACCOUNT_SID}
  apiKey: ${TWILIO_API_KEY}
  apiSecret: ${TWILIO_API_SECRET}
  #To be able to support conversations across organizations, we only use one serviceSid for the whole application.
  conversationServiceSid: ${TWILIO_CHAT_SERVICE_SID}
