version: "3.9"

services:
  # Guideline: https://meta.stoplight.io/docs/prism/ZG9jOjky-installation
  # Detail document for Twilio's Open API Spec:
  #   - Guideline for using Twilio's Open API Spec: https://www.twilio.com/docs/openapi/structure-of-twilio-openapi-spec
  #   - Twilio's Open API Spec: https://github.com/twilio/twilio-oai/tree/main/spec/json
  #   - https://www.twilio.com/docs/openapi/mock-api-generation-with-twilio-openapi-spec
  #   - Prism with many json files: https://meta.stoplight.io/docs/prism/ZG9jOjE2MDY1Njcx-serving-multiple-open-api-documents
  twilio:
    image: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - '8001:80'
    depends_on:
      - twilio_chat
      - twilio_accounts
      - twilio_conversations
  prism_1:
    image: stoplight/prism:4
    command: 'mock -p 4010 --host 0.0.0.0 https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml'
  twilio_chat:
    image: stoplight/prism:4
    command: 'mock -p 4010 --host 0.0.0.0 https://raw.githubusercontent.com/twilio/twilio-oai/main/spec/json/twilio_chat_v3.json'
  twilio_accounts:
    image: stoplight/prism:4
    command: 'mock -p 4010 --host 0.0.0.0 https://raw.githubusercontent.com/twilio/twilio-oai/main/spec/json/twilio_accounts_v1.json'
  twilio_conversations:
    image: stoplight/prism:4
    # config --host 0.0.0.0 will help us to access `http:localhost:8001` from local machine.
    command: 'mock -p 4010 --host 0.0.0.0 https://raw.githubusercontent.com/twilio/twilio-oai/main/spec/json/twilio_conversations_v1.json'